V2.6.0 jiraplugin-350 piwik add new indicators
everit-org/jira-timetracker-plugin pull request #329
Opened 2016-09-16 12:58 UTC by kalina91

Add analytic data sending to Non-working and Non-estimated input fields.
In JiraTimetrackerPluginImpl class, at the end of the afterPropertiesSet method, send the analytics data. The username is udetermined, so use "uknow" as username.

2016-09-19 12:43 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +    ALL("all"), NONE("none"), SELECTED("selected");
Please use breake lines when listing enums.

2016-09-19 12:44 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  private enum NonEstUsageValues {
Please put this to a independent class.

2016-09-19 12:47 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  public NoEstimateUsageChangedEvent(final String pluginId,
Don't use List<?>. We need a String and a Pattern constuctor. Then convert the Pattern List to String List

2016-09-19 12:48 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  private NonEstUsageValues decideNonEstValue(final List<?> collectorIssuePatterns) {
Only handle List<String> parameter. The code will be more readable.

2016-09-19 12:57 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +    ALL("all"), NONE("none"), SELECTED("selected");
CreateReportEvent class contains an enum ActiveFilterConditionName. Please put this to an independent class.

2016-09-19 13:10 UTC, daniel-toth-everit requested changes

2016-09-19 13:10 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +      "http://customer.jira.com/secure/ReportingWebAction!default.jspa";
Change the URL and to "http://customer.jira.com/secure/admin/JiraTimetrackerAdminSettingsWebAction!default.jspa";

2016-09-19 13:10 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NonWorkingUsageEvent.java
> +      "http://customer.jira.com/secure/ReportingWebAction!default.jspa";
Change the URL and to "http://customer.jira.com/secure/admin/JiraTimetrackerAdminSettingsWebAction!default.jspa";

2016-09-20 07:19 UTC, kalina91 commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  private enum NonEstUsageValues {
Tell me some reason why? I think this is the most encapsulated solution. There is no other class which need to know anything about this class.

2016-09-20 07:20 UTC, kalina91 commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +    ALL("all"), NONE("none"), SELECTED("selected");
Duplication.

2016-09-20 07:29 UTC, kalina91 commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  public NoEstimateUsageChangedEvent(final String pluginId,
You think in this way?
`public class NoEstimateUsageChangedEvent {

  private List b;

  public NoEstimateUsageChangedEvent(final List<Pattern> b) {
    this.b = b;
  }

  public NoEstimateUsageChangedEvent(final List<String> b) {
    this.b = b;
  }
}`
It cause compile error.

2016-09-20 07:41 UTC, kalina91 commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  private NonEstUsageValues decideNonEstValue(final List<?> collectorIssuePatterns) {
If remove the ? type parameter, the compiler make extra warning, I hate unnecessary warnings, and I know it it is a raw type. I make a fix that handle unexpected behavior.

2016-09-20 08:32 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +    ALL("all"), NONE("none"), SELECTED("selected");
Nope. It is an other class with other enums. Not you writed this part of code but it would be nice to get an unified solution.

2016-09-20 08:36 UTC, daniel-toth-everit commented on src/main/java/org/everit/jira/analytics/event/NoEstimateUsageChangedEvent.java
> +  public NoEstimateUsageChangedEvent(final String pluginId,
My idea was more like this:

public NoEstimateUsageChangedEvent(final List<Pattern> b) {
this(convertToStringList(b))
}

public NoEstimateUsageChangedEvent(final List<String> b) {
this.b = b;
}

Like this you can use a List<String> parameter in the decideNonEstValue method and get a more simple solution.

2016-09-22 07:02 UTC, daniel-toth-everit approved these changes

2016-09-22 07:03 UTC, merged